refactor: move scripts to root and use pnpm
freeCodeCamp/scripts pull request #200
Opened 2023-04-06 17:44 UTC by raisedadead

This PR moves the script packages into the repo root and uses pnpm

2023-04-06 19:27 UTC, ShaunSHamilton requested changes
Single borken point I could find. Seems unrelated, but is still braking due to workspaces.

Which brings me to: Do we really want all of these unrelated scripts to be a part of a workspace?

To be honest, I just dislike the need to install 100s of unrelated root npm packages just because I wanted to run a single script with 2 root deps.

2023-04-06 19:27 UTC, ShaunSHamilton commented on tricky-challenges/package.json
This workspace needs a peerdep of `@types/node` installed.

2023-04-06 22:03 UTC, raisedadead commented
Agreed. I will update this in the morning.

2023-04-07 10:09 UTC, ojeytonwilliams commented
Given that it takes all of 3 seconds to install everything, I'd just go with workspaces. It seems simpler to me.

> install 100s of unrelated root npm packages just because I wanted to run a single script with 2 root deps.

Even that shouldn't be a problem if https://github.com/pnpm/pnpm/issues/6300 is fixed.

2023-04-07 10:42 UTC, ShaunSHamilton approved these changes
I am happy with this 👍

2023-04-07 11:09 UTC, merged

2023-04-07 11:10 UTC, raisedadead commented
Merging because I want to add a few scripts I have lying around.