feat: migrate Ghost to Strapi script
freeCodeCamp/scripts pull request #210
Opened 2023-10-13 12:22 UTC by Sembauke

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

2023-10-24 13:20 UTC, raisedadead commented
Yes - go ahead.

2023-10-24 13:54 UTC, Nirajn2311 commented on news/strapi-migration.js
> +  const strapiUsers = await uploadUsersToCMS();
Thanks for catching that. I missed it while testing out the code.

2023-10-24 15:49 UTC, sidemt requested changes

2023-10-27 09:39 UTC, sidemt approved these changes
LGTM

2023-10-27 09:40 UTC, merged